name: Semantic Release

on:
  push:
    branchs: ["main"]

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm ci
      - run: npm run build
      - run: npx semantic-release --branches main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
